export const ROUTES = {
  ROOT: '/',
  LOGIN: '/auth/login',
  TREE_SCREENING: '/tree-screening',
  TISSUE_DEVELOPMENT: '/tissue-development',
  ENTER_INFECTED_SAMPLE_INFORMATION: '/enter-infected-sample-information',
  SCAN_FOR_INFECTED_SAMPLES: '/scan-for-infected-samples',
  ENVIRONMENT: '/environment',
  BRIGHT_ROOM: '/bright-room',
  USER: '/user',
  USER_MANAGEMENT: '/user-management',
  PTCM_LOGIN: 'auth/login',
  LOV: 'settings/lov',
  CATEGORY: '/category',
  GLOBALSETTING: 'settings/global',
  ORDERS: '/orders',
  CREATEORDER: '/orders/create',
  SUBCULTURING: '/subculturings',
  INITIATECULTURE: '/initiatecultures',
  CULTURINGCELL: '/culturingcells',
};
